BANDEIRAS: dict[str, str] = {
    # América do Sul
    "Brasil": "🇧🇷",
    "Argentina": "🇦🇷",
    "Uruguai": "🇺🇾",
    "Colômbia": "🇨🇴",
    "Chile": "🇨🇱",
    "Equador": "🇪🇨",
    "Peru": "🇵🇪",
    "Paraguai": "🇵🇾",
    "Venezuela": "🇻🇪",
    "Bolívia": "🇧🇴",
    # América do Norte e Central
    "México": "🇲🇽",
    "Estados Unidos": "🇺🇸",
    "EUA": "🇺🇸",
    "Canadá": "🇨🇦",
    "Costa Rica": "🇨🇷",
    "Honduras": "🇭🇳",
    "Panamá": "🇵🇦",
    "Jamaica": "🇯🇲",
    "El Salvador": "🇸🇻",
    "Guatemala": "🇬🇹",
    "Cuba": "🇨🇺",
    "Trinidad e Tobago": "🇹🇹",
    # Europa
    "França": "🇫🇷",
    "Alemanha": "🇩🇪",
    "Espanha": "🇪🇸",
    "Inglaterra": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Portugal": "🇵🇹",
    "Itália": "🇮🇹",
    "Holanda": "🇳🇱",
    "Países Baixos": "🇳🇱",
    "Bélgica": "🇧🇪",
    "Croácia": "🇭🇷",
    "Sérvia": "🇷🇸",
    "Suíça": "🇨🇭",
    "Dinamarca": "🇩🇰",
    "Polônia": "🇵🇱",
    "Ucrânia": "🇺🇦",
    "Turquia": "🇹🇷",
    "Áustria": "🇦🇹",
    "Suécia": "🇸🇪",
    "Noruega": "🇳🇴",
    "Escócia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "País de Gales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "Grécia": "🇬🇷",
    "República Tcheca": "🇨🇿",
    "Eslováquia": "🇸🇰",
    "Hungria": "🇭🇺",
    "Romênia": "🇷🇴",
    "Eslovênia": "🇸🇮",
    "Albânia": "🇦🇱",
    "Geórgia": "🇬🇪",
    "Bósnia e Herzegovina": "🇧🇦",
    # África
    "Marrocos": "🇲🇦",
    "Senegal": "🇸🇳",
    "Nigéria": "🇳🇬",
    "Camarões": "🇨🇲",
    "Costa do Marfim": "🇨🇮",
    "Gana": "🇬🇭",
    "Egito": "🇪🇬",
    "Argélia": "🇩🇿",
    "Tunísia": "🇹🇳",
    "Mali": "🇲🇱",
    "África do Sul": "🇿🇦",
    "Angola": "🇦🇴",
    "Etiópia": "🇪🇹",
    "Tanzania": "🇹🇿",
    "República Democrática do Congo": "🇨🇩",
    # Ásia
    "Japão": "🇯🇵",
    "Coreia do Sul": "🇰🇷",
    "Irã": "🇮🇷",
    "Arábia Saudita": "🇸🇦",
    "Austrália": "🇦🇺",
    "Catar": "🇶🇦",
    "Qatar": "🇶🇦",
    "China": "🇨🇳",
    "Índia": "🇮🇳",
    "Iraque": "🇮🇶",
    "Jordânia": "🇯🇴",
    "Uzbequistão": "🇺🇿",
    # Oceania
    "Nova Zelândia": "🇳🇿",
    "Fiji": "🇫🇯",
}


def bandeira(pais: str) -> str:
    return BANDEIRAS.get(pais.strip(), "")
